Models/ContentTreeAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Orchard.ContentTree.Models {
    public enum ContentTreeAction {
        Delete,
        Unpublish,
        Publish,
        PublishDraft
    }
}

Models/ContentTreeItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement;

namespace Orchard.ContentTree.Models {
    public class ContentTreeItem {
        public string Path { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public int Level { get; set; }
        public ContentPart Content { get; set; }

        public List<ContentTreeItem> Children { get; set; }
    }
}

Models/ContentTreeSettingsPart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement;
using Orchard.ContentManagement.Records;

namespace Orchard.ContentTree.Models {
    public class ContentTreeSettingsPart : ContentPart<ContentTreeSettingsRecord> {
        public string[] IncludedTypes {
            get {
                if (String.IsNullOrEmpty(Record.IncludedTypes)) {
                    return new string[0];
                }
                else {
                    return Record.IncludedTypes.Split(';');
                }

            }
            set{
                Record.IncludedTypes = String.Join(";", value);
            }
        }
    }

    public class ContentTreeSettingsRecord : ContentPartRecord {
        public virtual string IncludedTypes { get; set; }
    }
}

ViewModels/ContentTreeSettingsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Orchard.ContentTree.ViewModels {
    public class ContentTreeSettingsViewModel {
        public SelectListItem[] SelectedTypes { get; set; }
    }
}

ViewModels/ContentTreeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Orchard.ContentManagement;

namespace Orchard.ContentTree.ViewModels {
    public class ContentTreeViewModel {
        public dynamic Tree { get; set; }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using Orchard.Autoroute.Models;
using Orchard.ContentManagement;
using Orchard.ContentTree.Models;
using Orchard.ContentTree.Services;
using Orchard.ContentTree.ViewModels;
using Orchard.Core.Title.Models;
using Orchard.DisplayManagement;
using Orchard.Mvc;

namespace Orchard.ContentTree.Controllers {
    public class AdminController : Controller {
        private readonly IOrchardServices _services;
        private readonly IContentTreeService _contentTreeService;
        private readonly IShapeFactory _shapeFactory;

        public AdminController(
            IOrchardServices services, 
            IContentTreeService contentTreeService, 
            IShapeFactory shapeFactory) 
        {
            _services = services;
            _contentTreeService = contentTreeService;
            _shapeFactory = shapeFactory;
        }

        public ActionResult ContentTree() {
            return View();
        }

        public ActionResult ContentTreeAsync() {
            var treeModel = _contentTreeService.BuildTree();

            var viewModel = new ContentTreeViewModel
            {
                Tree = _contentTreeService.Display(treeModel)
            };

            return PartialView("ContentTreePartial", viewModel);
        }

        [HttpGet]
        public ActionResult SaveActions(int id, ContentTreeAction actions) {
            var contentManager = _services.ContentManager;

            var item = contentManager.Get(id, VersionOptions.Latest);

            if (item != null) {
                switch (actions)
                {
                    case ContentTreeAction.Delete: {
                            contentManager.Remove(item);

                            break;
                        }
                    case ContentTreeAction.Unpublish: {
                            contentManager.Unpublish(item);

                            break;
                        }
                    case ContentTreeAction.Publish:
                    case ContentTreeAction.PublishDraft:
                        {
                            contentManager.Publish(item);

                            break;
                        }
                }

                if (Request.IsAjaxRequest()) {
                    var shape = _contentTreeService.Display(_contentTreeService.GetTreeItem(item));
                    var html = _contentTreeService.Render(ControllerContext, TempData, "TreeItem", shape);

                    return Json(new { Id = id, Action = actions.ToString(), ItemHtml = html }, JsonRequestBehavior.AllowGet);
                }
            }

            return RedirectToAction("ContentTree");
        }

        [HttpGet]
        public ActionResult Settings() {
            var settings = _contentTreeService.GetSettings();

            var model = new ContentTreeSettingsViewModel();

            model.SelectedTypes = _contentTreeService.ContentTypeOptions(settings.IncludedTypes).ToArray();

            return View(model);
        }

        [HttpPost, ActionName("Settings")]
        public ActionResult SettingsPost(ContentTreeSettingsViewModel model) {
            var settings = _contentTreeService.GetSettings();

            settings.IncludedTypes = model.SelectedTypes.Where(t => t.Selected).Select(t => t.Value).ToArray();

            model.SelectedTypes = _contentTreeService.ContentTypeOptions(settings.IncludedTypes).ToArray();

            return View("Settings", model);
        }
    }
}

Views/Admin/ContentTree.cshtml
@{
    Script.Require("Orchard_ContentTree");
    Style.Require("Orchard_ContentTree");

    Layout.Title = "Content Tree";
}
<fieldset class="content-tree-fields">
    <legend>@T("Content Tree")</legend>
    <p class="hint">@T("The content tree only shows items which have a route (URL).")</p>
    <div class="content-tree-clear"></div>
    <div class="content-tree-key">
        <div class="left-column">
            <p class="placeholder">Tree placeholder.</p>
            <p class="uneditable">Item you can't edit.</p>
        </div>
        <div class="right-column">
            <p class="delete">Unsaved deleted item.</p>
            <p class="unpublish">Unpublished item.</p>
        </div>
        <div class="content-tree-clear"></div>
    </div>
    <div class="blanket-actions">
        <a href="#" class="button primaryAction Toggle_Editable">Show only items I can edit</a>
        <a href="#" class="button primaryAction Expand_All">Expand All</a>
        <a href="#" class="button primaryAction Collapse_All">Collapse All</a>
    </div>
    <div class="content-tree-clear"></div>
    <div class="content-tree">
        <p class="content-tree-spinner">@T("Loading content tree...")</p>
        <p class="hint">This can sometimes take a short while, depending on the number of content items in the site.</p> 
    </div>
    
</fieldset>




Views/Admin/ContentTreePartial.cshtml
@model Orchard.ContentTree.ViewModels.ContentTreeViewModel
@Display(Model.Tree)



Views/Admin/Settings.cshtml
@model Orchard.ContentTree.ViewModels.ContentTreeSettingsViewModel
@{
    Layout.Title = "Content Tree Settings";
    int ti = 0;
}
@using (Html.BeginFormAntiForgeryPost()) {
<fieldset>
    <legend>@T("Types to include in Content Tree")</legend>
    <ul>
        @foreach (var type in Model.SelectedTypes) {
            @Html.HiddenFor(m => m.SelectedTypes[ti].Value)
            <li><label for="@Html.FieldIdFor(m => m.SelectedTypes[ti].Selected)">@Html.CheckBoxFor(m => m.SelectedTypes[ti].Selected) @type.Text</label></li>
            ti++;
        }
    </ul>
    <button class="button primaryAction" value="submit.Save" id="submit.Save" name="submit.Save">Save</button>
</fieldset>
}


Views/Parts/TreeItem.cshtml
@using Orchard.Core.Contents;
@using Orchard.ContentManagement;
@using Orchard.Utility.Extensions;
@{
    string hiddenId = String.Format("Actions_{0}", Model.Content.Id);

    bool hasPublished = ((ContentPart)Model.Content).HasPublished();
    bool hasDraft = ((ContentPart)Model.Content).HasDraft();
    bool hasChildren = Model.Children != null && Model.Children.Count > 0;
    
    string unpublished = (hasDraft | !hasPublished) ? "Unpublished" : "";
    string noEdit = Model.Editable ? "" : "no-edit";
    string noHide = Model.NoHide ? "" : "can-hide";

}

@if (hasChildren) {
    <a href="#" class="tree-expando @if(Model.Level > 0) { <text>closed</text> }"></a>
}
<div class="tree-item @unpublished @noEdit @noHide" data-path="@Model.Path" data-level="@Model.Level">
    <div class="properties">
        <p>@Html.ItemDisplayLink((string)Model.Title, (IContent)Model.Content) <span class="path"><em>/@Model.Path</em></span></p>
    </div>
    @if(Model.Editable) {
        <div class="related">
            @Html.Hidden(hiddenId, "", new { @class = "actions" })
            @Display(Model.Actions) 
        </div>
    }
</div>
@if (hasChildren) {
    <ul @if(Model.Level > 0) { <text>style="display:none;"</text> }>
        @foreach (var child in Model.Children) {
            <li>@Display(child)</li>
        }
    </ul>
}

Views/Parts/TreeItemActions.cshtml
@using Orchard.Core.Contents;
@using Orchard.ContentManagement;
@using Orchard.Utility.Extensions;

@{
    Script.Require("ShapesBase");
    ContentPart contentPart = Model.ContentPart;
}
<div class="manage-actions">
    @if (Authorizer.Authorize(Permissions.EditContent, (IContent)Model.ContentPart.ContentItem)) {
        @Html.ItemEditLink(T("Edit").Text, (IContent)Model.ContentPart.ContentItem, new { returnUrl = Request.ToUrlString() })@T(" | ")
    }
    @if (contentPart.HasPublished()) {
        @Html.ItemDisplayLink(T("View").Text, (ContentItem)Model.ContentPart.ContentItem)
        @T(" | ")

        if (contentPart.HasDraft()) {
            @Html.Link(T("Publish Draft").Text, Url.Action("Publish", "Admin", new { area = "Contents", id = contentPart.ContentItem.Id, returnUrl = Request.ToUrlString() }))
            @T(" | ")

            if (Authorizer.Authorize(Permissions.PublishContent, contentPart)) {
                @Html.ActionLink(T("Preview").Text, "Preview", "Item", new {area = "Contents", id = ((ContentItem) Model.ContentPart.ContentItem).Id})
                @T(" | ")
            }
        }

        if (Authorizer.Authorize(Permissions.PublishContent, contentPart)) {
            @Html.Link(T("Unpublish").Text, Url.Action("Unpublish", "Admin", new {area = "Contents", id = contentPart.ContentItem.Id, returnUrl = Request.ToUrlString()}))
            @T(" | ")
        }
     } else {
        if ( contentPart.HasDraft() ) {    
            @Html.ActionLink(T("Preview").Text, "Preview", "Item", new { area = "Contents", id = ((ContentItem)Model.ContentPart.ContentItem).Id })
            @T(" | ")
        }

        if (Authorizer.Authorize(Permissions.PublishContent, contentPart)) {
            @Html.Link(T("Publish").Text, Url.Action("Publish", "Admin", new {area = "Contents", id = contentPart.ContentItem.Id, returnUrl = Request.ToUrlString()}))
            @T(" | ")
        }
    }

    @if (Authorizer.Authorize(Permissions.DeleteContent, (IContent)Model.ContentPart.ContentItem)) {
        if (!Model.HasChildren) {
            @Html.Link(T("Delete").Text, Url.ItemRemoveUrl((IContent)Model.ContentPart.ContentItem, new { returnUrl = Request.ToUrlString() }))
        }
        else{
            <span title="@T("You may not delete an item until all it's children have been deleted.")">@T("Delete")</span>
        }
    }
</div>

Views/Parts/TreePlaceholder.cshtml
@using Orchard.Core.Contents;
@using Orchard.ContentManagement;
@using Orchard.Utility.Extensions;
@{
    string noHide = Model.NoHide ? "" : "can-hide";
}
<div class="tree-node">
    @if (Model.Children != null) {
        <a href="#" class="tree-expando @if(Model.Level > 0) { <text>closed</text> }"></a>
    }
    <div class="tree-item placeholder @noHide" data-path="@Model.Path" data-level="@Model.Level">
        <div class="properties">
            <p>@Model.Title <span class="path"><em>/@Model.Path</em></span></p>
        </div>
    </div>
    @if (Model.Children != null) {
        <ul @if(Model.Level > 0) { <text>style="display:none;"</text> }>
            @foreach (var child in Model.Children) {
                <li>@Display(child)</li>
            }
        </ul>
    }
</div>